Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MoviesDBManager.Models;

namespace MoviesDBManager.Controllers
{
    public class ActorsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Actors(bool forceRefresh = false)
        {
            if (forceRefresh || DB.Actors.HasChanged)
            {
                return PartialView(DB.Actors.ToList().OrderBy(c => c.Name));
            }
            return null;
        }
        public ActionResult ActorForm(Actor actor)
        {
            return PartialView(actor);
        }

        public ActionResult Create()
        {
            ViewBag.Castings = null;
            ViewBag.Movies = SelectListUtilities<Movie>.Convert(DB.Movies.ToList());
            return View(new Actor());
        }

        [HttpPost]
        public ActionResult Create(Actor actor, List<int> SelectedItems)
        {
            if (ModelState.IsValid)
            {
                DB.Actors.Add(actor, SelectedItems);
                return RedirectToAction("Index");
            }
            ViewBag.Castings = SelectListUtilities<Movie>.Convert(actor.Movies);
            ViewBag.Movies = SelectListUtilities<Movie>.Convert(DB.Movies.ToList());
            return View();
        }

        public ActionResult Details(int id)
        {
            Actor actor = DB.Actors.Get(id);
            if (actor != null)
            {
                return View(actor);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            Actor actor = DB.Actors.Get(id);
            if (actor != null)
            {
                ViewBag.Castings = SelectListUtilities<Movie>.Convert(actor.Movies);
                ViewBag.Movies = SelectListUtilities<Movie>.Convert(DB.Movies.ToList());
                return View(actor);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Actor actor, List<int> SelectedItems)
        {
            if (ModelState.IsValid)
            {
                DB.Actors.Update(actor, SelectedItems);
                return RedirectToAction("Index");
            }
            ViewBag.Movies = SelectListUtilities<Movie>.Convert(actor.Movies);
            ViewBag.Movies = SelectListUtilities<Movie>.Convert(DB.Movies.ToList());
            return View(actor);
        }

        public ActionResult Delete(int id)
        {
            DB.Actors.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/MoviesController.cs
using MoviesDBManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviesDBManager.Controllers
{
    public class MoviesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Movies(bool forceRefresh = false)
        {
            if (forceRefresh || DB.Movies.HasChanged)
            {
                return PartialView(DB.Movies.ToList().OrderBy(c => c.Name));
            }
            return null;
        }
        public ActionResult MovieForm(Movie movie)
        {
            return PartialView(movie);
        }

        public ActionResult Create()
        {
            ViewBag.Castings = null;
            ViewBag.Actors = SelectListUtilities<Actor>.Convert(DB.Actors.ToList());
            return View(new Movie());
        }

        [HttpPost]
        public ActionResult Create(Movie movie, List<int> SelectedItems)
        {
            if (ModelState.IsValid)
            {
                DB.Movies.Add(movie, SelectedItems);
                return RedirectToAction("Index");
            }
            ViewBag.Castings = SelectListUtilities<Actor>.Convert(movie.Actors);
            ViewBag.Actors = SelectListUtilities<Actor>.Convert(DB.Actors.ToList());
            return View();
        }
        public ActionResult Details(int id)
        {
            Movie movie = DB.Movies.Get(id);
            if (movie != null)
            {
                return View(movie);
            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            Movie movie = DB.Movies.Get(id);
            if (movie != null)
            {
                ViewBag.Castings = SelectListUtilities<Actor>.Convert(movie.Actors);
                ViewBag.Actors = SelectListUtilities<Actor>.Convert(DB.Actors.ToList());
                return View(movie);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Movie movie, List<int> SelectedItems)
        {
            if (ModelState.IsValid)
            {
                DB.Movies.Update(movie, SelectedItems);
                return RedirectToAction("Index");
            }
            ViewBag.Castings = SelectListUtilities<Actor>.Convert(movie.Actors);
            ViewBag.Actors = SelectListUtilities<Actor>.Convert(DB.Actors.ToList());
            return View();
        }
        public ActionResult Delete(int id)
        {
            DB.Movies.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/Movies/Index">
                    <img src="/favicon.ico" style="height:48px" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Acteurs", "Index", "Actors")</li>
                    <li>@Html.ActionLink("Films", "Index", "Movies")</li>
                    <li>@Html.ActionLink("À propos", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Répertoire de films</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>